[project]
name = "nyc-taxi-realtime-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "simulated-gps-producer",
]
